In [1]:
import numpy as np

In [9]:
# Initialization with lists

v1 = np.array([1.0, 2.0])
v2 = np.array([1.0, 1.0])

In [10]:
# Inner product

np.inner(v1, v2)

3.0

In [11]:
# Addition

v1+v2

array([2., 3.])

In [12]:
# Scalar multiplication

3*v1

array([3., 6.])

In [8]:
# Random initialization with N(0,1)

np.random.normal(size=2)

array([ 0.85961796, -0.92624892])

In [ ]:
import random
from math import exp, log

X = [(0,0), (1,0), (0,1), (1,1)]
Y = [0,0,0,1]

class logistic_regression_model():
    def __init__(self):
        self.w = [random.random(), random.random()]
        self.b = random.random()
        
    def sigmoid(self, z):
        return 1/(1 + exp(-z))
    
    def predict(self, x):
        z = self.w[0] * x[0] + self.w[1] * x[1] + self.b
        a = self.sigmoid(z)
        return a

model = logistic_regression_model()

def train(X, Y, model, lr = 0.1):
    dw0 = 0.0
    dw1 = 0.0
    db = 0.0
    m = len(X)
    cost = 0.0
    for x, y in zip(X, Y):
        a = model.predict(x)
        if y == 1:
            cost -= log(a)
        else:
            cost -= log(1-a)
            
        dw0 += (a-y)*x[0]
        dw1 += (a-y)*x[1]
        db += (a-y)
            
    cost /= m
    model.w[0] -= lr * dw0/m
    model.w[1] -= lr * dw1/m
    model.b -= lr * db/m
        
    return cost

for epoch in range(10000):
    cost = train(X, Y, model, 0.1)
    if epoch % 100 == 0:
        print(epoch, cost)

model.predict((0, 0))
model.predict((0, 1))
model.predict((0, 1))
model.predict((1, 1))