In [7]:
#
# Accessing elements
#

In [8]:
# Access
arr_t = torch.Tensor([[1,2],[2,3]])
arr_t[0,1]

tensor(2.)

In [9]:
# Get a Python number
arr_t[0,1].item()

2.0

In [10]:
# Update
arr_t[0,1] = 0
arr_t

tensor([[1., 0.],
        [2., 3.]])

In [11]:
#
# Slicing
#

In [12]:
t = torch.Tensor([[1,2,3,4], [2,3,4,5], [5,6,7,8]])
print(t)

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [5., 6., 7., 8.]])


In [13]:
t[:2]

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.]])

In [14]:
t[:,1:]

tensor([[2., 3., 4.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [15]:
t[1:,1:3]

tensor([[3., 4.],
        [6., 7.]])

In [16]:
t[1:, 1:3] = 0
print(t)

tensor([[1., 2., 3., 4.],
        [2., 0., 0., 5.],
        [5., 0., 0., 8.]])


In [17]:
#
# Negative slicing
#

In [18]:
t = torch.Tensor([[1,2,3,4], [2,3,4,5], [5,6,7,8]])
print(t)

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [5., 6., 7., 8.]])


In [19]:
t[:,:-1]

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [5., 6., 7.]])

In [20]:
t[:,-3:-1]

tensor([[2., 3.],
        [3., 4.],
        [6., 7.]])

In [ ]:
#
# Shape & Transpose (matrix)
#

In [24]:
X = torch.Tensor([[1,2,3], [4,5,6]])

In [25]:
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [26]:
X.T

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [27]:
print(X.shape)
print(X.T.shape)

torch.Size([2, 3])
torch.Size([3, 2])


In [28]:
#
# Sum
#

In [29]:
print(X.sum())

tensor(21.)


In [30]:
print(X.sum(0))
print(X.sum(1))

tensor([5., 7., 9.])
tensor([ 6., 15.])


In [32]:
print(X.sum(0, keepdim = True))
print(X.sum(1, keepdim = True))

tensor([[5., 7., 9.]])
tensor([[ 6.],
        [15.]])


In [33]:
#
# Mean
#

In [37]:
print(X.mean())
print(X.mean(0))
print(X.mean(1))

tensor(3.5000)
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])


In [38]:
#
# Max
#

In [40]:
X = torch.Tensor([[1,7,3], [4,5,6]])

In [41]:
X

tensor([[1., 7., 3.],
        [4., 5., 6.]])

In [42]:
print(X.max())
print(X.max(0))
print(X.max(1))

tensor(7.)
torch.return_types.max(
values=tensor([4., 7., 6.]),
indices=tensor([1, 0, 1]))
torch.return_types.max(
values=tensor([7., 6.]),
indices=tensor([1, 2]))


In [43]:
#
# Binary Operators
#

In [52]:
X = torch.Tensor([[1,2,3], [4,5,6]])
Y = torch.Tensor([[1,0,2], [1,0,1]])

In [53]:
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [54]:
Y

tensor([[1., 0., 2.],
        [1., 0., 1.]])

In [55]:
X+Y

tensor([[2., 2., 5.],
        [5., 5., 7.]])

In [56]:
X*Y

tensor([[1., 0., 6.],
        [4., 0., 6.]])

In [57]:
torch.matmul(X.T, Y)

tensor([[ 5.,  0.,  6.],
        [ 7.,  0.,  9.],
        [ 9.,  0., 12.]])

In [58]:
torch.matmul(X, Y.T)

tensor([[ 7.,  4.],
        [16., 10.]])

In [59]:
#
# Inner product
#

In [60]:
x = torch.FloatTensor([1,2])
y = torch.FloatTensor([1,1])

In [61]:
print(torch.inner(x,y))

tensor(3.)
