In [2]:
# torch.autograd is PyTorch's autpmatic differsntiation engine that powers neural network training
# Initialization: Set requires_grad to True if you want to track the gradient
import torch

w = torch.randn(2, requires_grad = True)
x = torch.ones(2)

print("w", w.requires_grad)
print("x", x.requires_grad)

w True
x False


In [3]:
#
# Example
#

In [12]:
# 1. Initialize
w = torch.randn(2, requires_grad = True)
x = torch.Tensor([1,2])

# 2. Predict output
y_hat = torch.inner(w,x)

# 2-2. Intermediate results
print(x)
print(w)
print(y_hat)
print('\n')

# 3. Compute loss
loss = (x.mean()-y_hat)**2
print(loss)

# 4. Backpropagation
loss.backward()

# 4-2. Accessing the gradient
w.grad

tensor([1., 2.])
tensor([-1.4089, -1.2847], requires_grad=True)
tensor(-3.9784, grad_fn=<ViewBackward0>)


tensor(30.0124, grad_fn=<PowBackward0>)


tensor([-10.9567, -21.9134])

In [14]:
# Manual parameter update
lr = 0.1

with torch.no_grad():
    w = w-lr * w.grad
print(w.requires_grad)
w.requires_grad = True

False
