In [4]:
# Initialize with Python lists
import torch
import numpy as np

arr = [[1,2], [2,3]]

In [5]:
# Numpy
arr_n = np.array(arr)
print(type(arr_n))
print(arr_n)

# PyTorch
arr_t = torch.Tensor(arr)
print(type(arr_t))
print(arr_t)

<class 'numpy.ndarray'>
[[1 2]
 [2 3]]
<class 'torch.Tensor'>
tensor([[1., 2.],
        [2., 3.]])


In [7]:
# Initialization: ones & zeros

# Numpy
print(np.ones((2,3)))
print(np.zeros((2,3)))

# PyTorch
print(torch.ones((2,3)))
print(torch.zeros((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# Initialization: ones_like & zeros_like

# Numpy
print(np.ones_like(arr_n))
print(np.zeros_like(arr_n))

# PyTorch
print(torch.ones_like(arr_t))
print(torch.zeros_like(arr_t))

[[1 1]
 [1 1]]
[[0 0]
 [0 0]]
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [16]:
# Two ways of specifying data type

# 1. Use keyword argument dtype
print(torch.ones((2,3), dtype = torch.int))
print(torch.ones((2,3), dtype = torch.float))

# 2. Use typed tensors
ft = torch.FloatTensor([1,2])
print(ft)
print(ft.dtype)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([1., 2.])
torch.float32
